default: &default
  adapter: postgresql
  encoding: 'UTF-8'
  collation: 'ru_RU.UTF-8'
  ctype: 'ru_RU.UTF-8'
  template: template0
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: zbs_development

test:
  <<: *default
  database: zbs_test

production:
  <<: *default
  database: zbs_production
